### ISSUE TITLE
Need help to choose SHA256 implementation

### ISSUE THREAD

**Issue by dobromyslov** [jedisct1/rust-hmac-sha256#6]
I'm looking for SHA256 implementation for embedded and can't choose the proper one of several.

There are 4 no_std SHA256 implementations:
1. Yours.
2. DoumanAsh lhash - https://github.com/DoumanAsh/lhash/blob/master/src/sha256.rs
3. DaGenix rust-crypto - https://github.com/DaGenix/rust-crypto/blob/master/src/sha2.rs
4. RustCrypto hashes - https://github.com/RustCrypto/hashes/blob/master/sha2/src/sha256/soft.rs

Could you please tell what pros and cons does your implementation have compared to others?

**Comment by jedisct1** [comment]
No 3rd party dependencies.

API stability. New versions never change nor break the API ever. Your applications don't need to be constantly updated.
