### ISSUE TITLE
HKDF::Extract and RFC 5869

### ISSUE THREAD

**Issue by senevoldsen** [jedisct1/rust-hmac-sha256#7]
Is HKDF::Extract mean to apply RFC 5869 with SHA-256 as the hash function? I am getting unexpected outputs using HKDF::extract.

From https://datatracker.ietf.org/doc/html/rfc5869 HKDF-Extract is defined as (with HASH=SHA-256)

```
HKDF-Extract(salt, IKM) -> PRK
where
PRK = HKDF-Extract(salt, IKM) = HMAC-Hash(salt, IKM) = HMAC-SHA-256(salt, IKM)
```

But this is not the result I get. Instead the code as defined does not even use it as a MAC, and instead:

```rust
pub fn extract(salt: impl AsRef<[u8]>, ikm: impl AsRef<[u8]>) -> [u8; 32] {
        let mut h = Hash::new();
        h.update(ikm);
        h.update(salt);
        h.finalize()
    }
```

I would expect it to be something like.

```rust
pub fn extract(salt: impl AsRef<[u8]>, ikm: impl AsRef<[u8]>) -> [u8; 32] {
       let mut hmac = HMAC::new(&salt);
       hmac .update(ikm);
       hmac.finalize()
    }
```
or even simpler:
```rust
pub fn extract(salt: impl AsRef<[u8]>, ikm: impl AsRef<[u8]>) -> [u8; 32] {
       HMAC::mac(ikm, salt)
    }
```

**Comment by jedisct1** [comment]
Oops, indeed!

Thank you for reporting this! I'm going to tag a new release now.
